name: Build and Deploy to Azure App Service

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v4

     - name: Setup .NET
       uses: actions/setup-dotnet@v4
       with:
        dotnet-version: '6.0.x'

     - name: Restore
       run: dotnet restore ./WebAPI.sln

     - name: Build
       run: dotnet build ./WebAPI.sln --configuration Release --no-restore

     - name: Publish
       run:  dotnet publish ./WebAPI.sln --configuration Release --no-build
      

