name: Build and Deploy to Azure App Service

on:
  workflow_dispatch:
  push:
    branches:
    - main


env:
  AZURE_WEBAPP_NAME: susan-webapi
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build
      - name: Test with the dotnet CLI
        run: dotnet test

      - name: Deployment to Azure App Service
        uses : actions/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: " ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
          
            

