name: Build and Deploy to Azure App Service

on:
  workflow_dispatch:
 

env:
  AZURE_WEBAPP_NAME: susan-webapp
  AZURE_WEBAPP_PACKAGE_PATH: "."

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build and publish
      run: |
        dotnet build --configuration Release
        dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp' --no-build

    - name: Deployment to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp"
